// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LoggerVisualizerVsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "LoggerVisualizer.b55f442f-f4bb-4ef6-aa7c-43e35143862e";
        public const string Name = "Logger Visualizer";
        public const string Description = @"Logger Debug Visualizer for Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "0.1.0";
        public const string Author = "elmahio";
        public const string Tags = "visualizer, logging, logger, ilogger, debug, debugging";
    }
}
