name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nuget/setup-nuget@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Update version
      run: |
        (Get-Content -Path src\LoggerVisualizer\LoggerVisualizer.csproj) |
          ForEach-Object {$_ -Replace '<AssemblyVersion>0.1.0</AssemblyVersion>', '<AssemblyVersion>0.2.${{ github.run_number }}</AssemblyVersion>'} |
            Set-Content -Path src\LoggerVisualizer\LoggerVisualizer.csproj
    - name: Restore
      run: nuget restore
    - name: Build
      run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
    - uses: actions/upload-artifact@v4
      with:
        name: LoggerVisualizer.vsix
        path: src\LoggerVisualizer\bin\Release\net8.0-windows\LoggerVisualizer.vsix
    - name: Create Release
      id: create_release
      if: ${{ github.event_name == 'push' }}
      uses: softprops/action-gh-release@v2
      with:
        files: src\LoggerVisualizer\bin\Release\net8.0-windows\LoggerVisualizer.vsix
        tag_name: 0.2.${{ github.run_number }}
        name: Release 0.2.${{ github.run_number }}
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}